server:
  port: 8080
 
spring:
  application:
    name: Crud
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost:27017/crud
    mongo.repositories.enabled: true
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      
      
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0